### ISSUE TITLE
Add a way to display only one error at a time

### ISSUE THREAD

**Issue by jrmlstf** [UltimateAngular/ngx-errors#34]
**Is this a feature request or a bug report?**
Feature request

**What was meant to happen?**
Add a global config and/or a way to display only one error a time. It should display the first error of the control errors associative array.

**Comment by jrmlstf** [comment]
A quick workaround in css could be : 
```css
[ngxErrors] {
  border: 1px solid theme-color("danger");
  padding: 0.5rem;

  [ngxError] {
    display: none;

    &:first-child {
      display: block;
    }
  }
}
```
